### ISSUE TITLE
Add type definitions for newrelic__pino-enricher inorder to provide support for typescript

### ISSUE THREAD

**Issue by swanandvk** [newrelic/newrelic-node-log-extensions#83] opened 2022-12-02 16:45 UTC
## Is your feature request related to a problem? Please describe.

At the moment @newrelic/pino-enricher doesn't have type definitions available for integrating it with typescript projects
causing compilation issues.

https://www.npmjs.com/package/@newrelic/pino-enricher

## Feature Description
 - create type definitions for @newrelic/pino-enricher module
 -  `npm i --save-dev @types/newrelic__pino-enricher `
       or 
     `yarn add -D @types/newrelic__pino-enricher `
 
 should install required type definitions in-order to use it with typescript.

## Priority
[Really Want, Must Have, Blocker]

**Comment by bizob2828** [comment] 2022-12-02 19:17
Hi @swanandvk this is a duplicate of #74. As I mentioned in there, PRs are always welcome!  I'm closing this one

**Closed** 2022-12-02 19:17 UTC
Labels: feature-request, needs-triage
